AllCops:
  NewCops: enable
  Exclude:
    - '**/db/migrate/*'
    - '**/db/schema.rb'
    - '**/Gemfile.lock'
    - '**/rails'
    - '**/vendor/**/*'
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'