volumes:
  mysql:
    name: carton-caps-api-mysql
    external: true

services:
  web:
    build:
      context: .
    image: carton-caps-api-web
    container_name: carton-caps-api-web
    env_file: .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: ["wait-for-it", "--strict", "--timeout=60", "db:3306", "--", "./run.sh"]
    depends_on:
      - db
  db:
    image: arm64v8/mysql:8.0-oracle
    container_name: carton-caps-api-db
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306:3306'
